# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: your-email@domain.com
brand: Jhaz
headline: Photographer, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shotsbyswati.com" # the base hostname & protocol for your site
copyright: 2019 LuJha, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 673164

# Contacts
email: shashwat_181@yahoo.co.in
phone: +1-Not-Avail-Able

# Tracking
googleAnalitycsID: UA-83933844-1

